 input {
  file {
    path => "/home/siem/security.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => [
        "Failed password for %{WORD:user} from %{IP:src_ip}",
        "%{YEAR}-%{MONTHNUM}-%{MONTHDAY} LOGIN FAIL user=%{WORD:user} ip=%{IP:src_ip}",
        "authentication failure"
      ]
    }
  }
}
output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "gaVQn7v+1QH94_PN1L09"
    ssl_enabled => true
    ssl_verification_mode => "none"
    index => "siem-logs"
  }
  stdout { codec => rubydebug }
}
